inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Layout/EmptyComment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - "spec/**/*.rb"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Max: 40
  Exclude:
    # `context` in tests are blocks and get quite large, so exclude the test
    # directory from having to adhere to this rule.
    - "spec/**/*.rb"

Metrics/ClassLength:
  Exclude:
    # Test classes get quite large, so exclude the test directory from having
    # to adhere to this rule.
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 24

Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/HashEachMethods:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/ApplicationController:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false
